### PR TITLE
Fix second argument for `.splice`

### PR DESCRIPTION
**Pull request by spaceinvadev**
`Line 109`: In this exercise, we have to remove items 3 to 5 with `.splice`, i.e. we have to remove a total of 3 items (assumed from index 3 to index 5).

You passed in `(3, 5)` for the `.splice` method and this will result in the removal of 5 items starting at index 3. To remove items 3 to 5 (3 items), you should pass in `(3, 3)` for the `.splice` method, since the second argument corresponds to the amount of items to remove.

### CODE REVIEW

**Comment by wesbos** [comment]
thanks!

**Comment by caspervanpomeren** [comment]
Shouldn't this be
` .splice(2, 3);`
Instead of 
`.splice(3, 3);`

Because the text says:

> take out items 3 to 5 of your new toppings array with splice()

Which should translate to index 2, and not index 3, because since when do we count from item 0?

**Comment by spaceinvadev** [comment]
Hey, @caspervanpomeren.

I set it to `.splice(3, 3)` because as I said in the first comment:
> we have to remove items 3 to 5 with .splice, i.e. we have to remove a total of 3 items _(assumed from index 3 to index 5)_.

I _assumed_ that Wes _meant_ to remove items 3 to 5 by their indexes, i.e. from **index 3 to index 5**.

Of course, I could've also interpreted that he wanted to remove items 3 to 5 by referring to their ordinal positions (from the third to the fifth element), in which case, we should've set it to `.splice(2, 3)`.

By the way, exactly because we do count from 0 in JavaScript (like in almost every programming language), it could be set to `.splice(2, 3)`.

Again, it is a matter of interpretation. But in this case, Wes merged the PR which indicates that when he said _remove items 3 to 5_, he was referring to the items with index 3, 4, and 5, which is exactly what we achieve by setting it to `.splice(3, 3)`: remove a total of 3 items starting from index 3.

**Comment by caspervanpomeren** [comment]
Hey @spaceinvadev 

Let me clarify what I meant. 

My entire point is that I disagree with your assumptions, so this original one:

> (assumed from index 3 to index 5).

and later when repeated:

> I assumed that Wes meant to remove items 3 to 5 by their indexes, i.e. from index 3 to index 5.

Based on this text:

> take out items 3 to 5 of your new toppings array with splice()

I don't think you should make that assumption, especially when the target audience of this course are beginners. This only confuses people even further, especially when they just learned this (as you mentioned):

>  because we do count from 0 in JavaScript (like in almost every programming language)

In these exercises it is especially important to note the difference between counting in normal circumstances (starting from 1) and in JavaScript (starting from 0) and reinforce this difference with these examples. So that means item 3 shouldn't translate to index 3, but index 2.

I propose a change to either the comment text or to the code:

> take out items 3 to 5 of your new toppings array with splice()

to:

> take out elements 3 to 5 of your new toppings array with splice()

"items" -> "elements". The term elements gets used in the documentation of arrays and it starts with element0, so that way it makes sense with the solution.

Or change the code as previously mentioned:

> .splice(3, 3);

to:

> .splice(2, 3);

A final note:

> Again, it is a matter of interpretation. But in this case, Wes merged the PR which indicates that when he said remove items 3 to 5, he was referring to the items with index 3, 4, and 5, which is exactly what we achieve by setting it to .splice(3, 3): remove a total of 3 items starting at index 3.

Even if you are right with your assumption, I don't think you should allow any room for assumptions in this case. And the fact that wes merged the PR only means that it's an improvement (which I totally agree with), but it doesn't mean we can't improve any further.

**Comment by spaceinvadev** [comment]
Well, @caspervanpomeren, now you're making a very clear point, which I agree with.

Speaking of assumptions, though, wasn't it easier for you to communicate your point at first instead of _assumming_ people would get it right away?

Thanks for your clarification, anyway.

**Comment by caspervanpomeren** [comment]
> Speaking of assumptions, though, wasn't it easier for you to communicate your point at first instead of assumming people would get it right away?

Ha, that's fair.

Thanks btw for all your contributions to this github, every time I notice something wrong in the course, I almost always find an issue about that exact problem made by you.

**Pull request merged**
